services:
  jappy:
    platform: linux/arm64
    image: gastudil/courses:jappy-vscode
    container_name: dev-jappy
    hostname: dev-jappy
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/home/devuser/workspace
    environment:
      WORKSPACE: /home/devuser/workspace
    networks:
      - back_net

networks:
  back_net:
