services:
  jappy:
    image: gastudil/courses:jappy-jupyter
    container_name: dev-jappy
    hostname: dev-jappy
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/home/devuser/workspace
    networks:
      - back_net

networks:
  back_net:
